version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /Users/pedrofonseca/Documents/LSBU/MOC/CW2/mosquitto:/mosquitto/
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iot-door

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - iot-door

  db:
    image: influxdb:latest
    restart: always
    ports:
      - 8086:8086
    networks:
      - iot-door
    environment:
      - INFLUXDB_DB=grafana
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass

  web-server:
    build: .
    restart: always
    volumes:
      - /Users/pedrofonseca/Documents/LSBU/MOC/CW2/www:/home/node/app
      - /usr/app/node_modules
    ports:
      - 8080:5000
    networks:
      - iot-door
    depends_on:
      - db
      - mqtt 
    command: "npm start"
    
    
    
networks:
  iot-door:
    driver: bridge

volumes:
  www:
  mosquitto: